-- =====================================================================
-- RECADOS DA EQUIPE — comunicação interdisciplinar no prontuário TEAcolher
-- A nutricionista pede para a psicóloga observar algo, a fono responde a
-- pedido da neuropsicopedagoga etc. Cada recado fica amarrado ao usuário
-- atendido (registro clínico), endereçado a uma ÁREA (qualquer profissional
-- da área vê) ou a uma PESSOA específica, ou à equipe toda.
--
-- PRÉ-REQUISITO: sql_prontuario_teacolher.sql (cria perfil_atual e tabelas).
-- Como rodar: Supabase → SQL Editor → New query → colar tudo → Run.
-- Pode rodar mais de uma vez sem problema.
-- =====================================================================

CREATE TABLE IF NOT EXISTS prontuario_recados (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_atendido_id bigint NOT NULL REFERENCES usuarios_atendidos(id) ON DELETE CASCADE,
  -- respostas são linhas com parent_id apontando pro recado original
  parent_id bigint REFERENCES prontuario_recados(id) ON DELETE CASCADE,
  de_profissional_id bigint REFERENCES equipe(id),
  de_nome text,                                     -- nome gravado (exibe mesmo se sair da equipe)
  para_area text,                                   -- área destino (null se for pessoa/equipe toda)
  para_profissional_id bigint REFERENCES equipe(id),-- pessoa destino (null se for área/equipe toda)
  texto text NOT NULL,
  status text DEFAULT 'aberto',                     -- aberto | resolvido (só no recado raiz)
  resolvido_em timestamptz,
  resolvido_por_nome text,
  criado_por uuid DEFAULT auth.uid(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recados_usuario ON prontuario_recados(usuario_atendido_id);
CREATE INDEX IF NOT EXISTS idx_recados_abertos ON prontuario_recados(status) WHERE status = 'aberto';

ALTER TABLE prontuario_recados ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Autenticados leem recados" ON prontuario_recados;
CREATE POLICY "Autenticados leem recados" ON prontuario_recados
  FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Admin e tecnico escrevem recados" ON prontuario_recados;
CREATE POLICY "Admin e tecnico escrevem recados" ON prontuario_recados
  FOR INSERT WITH CHECK (perfil_atual() IN ('admin','tecnico'));
DROP POLICY IF EXISTS "Admin e tecnico atualizam recados" ON prontuario_recados;
CREATE POLICY "Admin e tecnico atualizam recados" ON prontuario_recados
  FOR UPDATE USING (perfil_atual() IN ('admin','tecnico'));
DROP POLICY IF EXISTS "Admin exclui recados" ON prontuario_recados;
CREATE POLICY "Admin exclui recados" ON prontuario_recados
  FOR DELETE USING (perfil_atual() = 'admin');
