-- =====================================================================
-- HISTÓRICO DE ALTERAÇÕES DA ANAMNESE — TEAcolher
-- As técnicas editam a anamnese em conjunto (cada uma a sua área). Esta tabela
-- guarda QUEM alterou, O QUE mudou (campo, valor antigo -> novo) e QUANDO.
-- Uma linha por campo alterado; os campos de um mesmo "salvar" compartilham o
-- mesmo "lote" (para a tela agrupar "nesta edição, Fulana mudou A, B e C").
--
-- PRÉ-REQUISITO: as tabelas anamneses, usuarios_atendidos, equipe e a função
-- perfil_atual() já devem existir (sql_prontuario_teacolher.sql / sql_anamnese_completa.sql).
-- Como rodar: Supabase -> SQL Editor -> New query -> colar tudo -> Run.
-- Pode rodar mais de uma vez sem problema (idempotente).
-- =====================================================================

CREATE TABLE IF NOT EXISTS anamnese_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anamnese_id bigint REFERENCES anamneses(id) ON DELETE CASCADE,
  usuario_atendido_id bigint REFERENCES usuarios_atendidos(id) ON DELETE CASCADE,
  editor_nome text,                                  -- nome de quem alterou (gravado, não sai por join)
  profissional_id bigint REFERENCES equipe(id),      -- profissional da equipe, quando houver
  lote text,                                          -- agrupa os campos de um mesmo "salvar"
  campo text,                                         -- chave do campo (ou __criacao__ na 1ª gravação)
  campo_label text,                                   -- rótulo legível do campo
  valor_antigo text,
  valor_novo text,
  criado_por uuid DEFAULT auth.uid(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_anamnese_hist_anamnese ON anamnese_historico(anamnese_id);
CREATE INDEX IF NOT EXISTS idx_anamnese_hist_usuario ON anamnese_historico(usuario_atendido_id);
CREATE INDEX IF NOT EXISTS idx_anamnese_hist_lote ON anamnese_historico(lote);

ALTER TABLE anamnese_historico ENABLE ROW LEVEL SECURITY;

-- Só admin e técnico leem o histórico (contém valores clínicos antigos/novos).
DROP POLICY IF EXISTS "Admin e tecnico leem historico anamnese" ON anamnese_historico;
CREATE POLICY "Admin e tecnico leem historico anamnese" ON anamnese_historico
  FOR SELECT USING (perfil_atual() IN ('admin','tecnico'));

-- Só admin e técnico gravam (o app escreve uma linha por campo alterado).
DROP POLICY IF EXISTS "Admin e tecnico gravam historico anamnese" ON anamnese_historico;
CREATE POLICY "Admin e tecnico gravam historico anamnese" ON anamnese_historico
  FOR INSERT WITH CHECK (perfil_atual() IN ('admin','tecnico'));

-- Auditoria é append-only: ninguém edita linha do histórico. Só o admin pode
-- apagar (limpeza pontual), se algum dia precisar.
DROP POLICY IF EXISTS "Admin apaga historico anamnese" ON anamnese_historico;
CREATE POLICY "Admin apaga historico anamnese" ON anamnese_historico
  FOR DELETE USING (perfil_atual() = 'admin');
