-- =====================================================================
-- PRONTUÁRIO TEACOLHER — Anamnese + PIA (Plano Individual de Atendimento)
-- Como rodar: Supabase → SQL Editor → New query → colar tudo → Run.
-- Obs.: assume ids numéricos (int8) em usuarios_atendidos e equipe, que é
-- o padrão do Supabase. Se der erro de tipo na FK, os ids são uuid — avisar.
-- =====================================================================

-- 1) ANAMNESE — uma ficha por usuário atendido (atualizável ao longo do tempo)
CREATE TABLE IF NOT EXISTS anamneses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_atendido_id bigint NOT NULL UNIQUE REFERENCES usuarios_atendidos(id) ON DELETE CASCADE,
  profissional_id bigint REFERENCES equipe(id),
  data_entrevista date DEFAULT CURRENT_DATE,
  entrevistado_nome text,
  entrevistado_parentesco text,
  queixa_principal text,
  historico_gestacao_parto text,
  desenvolvimento_inicial text,
  historico_saude text,
  medicacoes_em_uso text,
  alergias_restricoes text,
  acompanhamentos_externos text,
  escola_atual text,
  escola_serie_turno text,
  historico_escolar text,
  rotina_diaria text,
  alimentacao_sono text,
  comunicacao_interacao text,
  contexto_sociofamiliar text,
  beneficios_sociais text,
  rede_apoio text,
  observacoes text,
  criado_por uuid DEFAULT auth.uid(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2) PIA — histórico de planos por usuário (o "vigente" mais recente é o atual)
CREATE TABLE IF NOT EXISTS planos_individuais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_atendido_id bigint NOT NULL REFERENCES usuarios_atendidos(id) ON DELETE CASCADE,
  profissional_id bigint REFERENCES equipe(id),
  data_elaboracao date DEFAULT CURRENT_DATE,
  data_revisao_prevista date,
  situacao text DEFAULT 'vigente',            -- vigente | revisado | encerrado
  demandas_identificadas text,
  objetivo_geral text,
  metas jsonb DEFAULT '[]'::jsonb,            -- [{area, objetivo, estrategias, prazo, situacao}]
  frequencia_prevista text,
  participacao_familia text,
  encaminhamentos_rede text,
  resultado_revisao text,
  observacoes text,
  criado_por uuid DEFAULT auth.uid(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_planos_individuais_usuario ON planos_individuais(usuario_atendido_id);

-- 3) updated_at automático
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_anamneses_updated ON anamneses;
CREATE TRIGGER trg_anamneses_updated BEFORE UPDATE ON anamneses
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS trg_planos_individuais_updated ON planos_individuais;
CREATE TRIGGER trg_planos_individuais_updated BEFORE UPDATE ON planos_individuais
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- 4) Função auxiliar: perfil do usuário autenticado (admin/operacional/tecnico/diretoria).
-- Estava prevista no supabase_schema.sql mas não existe neste banco — criamos aqui.
-- SECURITY DEFINER para conseguir ler a tabela usuarios mesmo com RLS ativa.
CREATE OR REPLACE FUNCTION perfil_atual()
RETURNS TEXT AS $$
  SELECT perfil FROM usuarios WHERE id = auth.uid()
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

-- 5) RLS — leitura para autenticados; escrita para admin e técnico
ALTER TABLE anamneses ENABLE ROW LEVEL SECURITY;
ALTER TABLE planos_individuais ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Autenticados leem anamneses" ON anamneses;
CREATE POLICY "Autenticados leem anamneses" ON anamneses
  FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Admin e tecnico inserem anamneses" ON anamneses;
CREATE POLICY "Admin e tecnico inserem anamneses" ON anamneses
  FOR INSERT WITH CHECK (perfil_atual() IN ('admin','tecnico'));
DROP POLICY IF EXISTS "Admin e tecnico atualizam anamneses" ON anamneses;
CREATE POLICY "Admin e tecnico atualizam anamneses" ON anamneses
  FOR UPDATE USING (perfil_atual() IN ('admin','tecnico'));
DROP POLICY IF EXISTS "Admin exclui anamneses" ON anamneses;
CREATE POLICY "Admin exclui anamneses" ON anamneses
  FOR DELETE USING (perfil_atual() = 'admin');

DROP POLICY IF EXISTS "Autenticados leem planos individuais" ON planos_individuais;
CREATE POLICY "Autenticados leem planos individuais" ON planos_individuais
  FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Admin e tecnico inserem planos individuais" ON planos_individuais;
CREATE POLICY "Admin e tecnico inserem planos individuais" ON planos_individuais
  FOR INSERT WITH CHECK (perfil_atual() IN ('admin','tecnico'));
DROP POLICY IF EXISTS "Admin e tecnico atualizam planos individuais" ON planos_individuais;
CREATE POLICY "Admin e tecnico atualizam planos individuais" ON planos_individuais
  FOR UPDATE USING (perfil_atual() IN ('admin','tecnico'));
DROP POLICY IF EXISTS "Admin exclui planos individuais" ON planos_individuais;
CREATE POLICY "Admin exclui planos individuais" ON planos_individuais
  FOR DELETE USING (perfil_atual() = 'admin');

-- 6) Técnico precisa LER o cadastro dos usuários atendidos para preencher
-- anamnese/PIA e imprimir documentos completos (nome, nascimento, responsável).
-- Só tem efeito se usuarios_atendidos tiver RLS habilitado; é aditiva e não
-- mexe nas permissões de admin/operacional.
DROP POLICY IF EXISTS "Tecnico le usuarios atendidos" ON usuarios_atendidos;
CREATE POLICY "Tecnico le usuarios atendidos" ON usuarios_atendidos
  FOR SELECT USING (perfil_atual() = 'tecnico');
